FPS = 60
SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1020
BOARD_WIDTH = BOARD_HEIGHT = 720
DIMENSION = 8
SQUARE_SIZE = BOARD_HEIGHT // DIMENSION
SQUARE_COLORS = []
IMAGES = {}
TRANSPARENCY = 100
SOUNDS = {}